version: '3'

services: 
    api: 
        container_name: api-songs
        restart: always
        build: .
        ports: 
          - "4000:5000"
        links:
          - mongo
    mongo: 
        container_name: mongoDB
        image: mongo
        ports: 
          - "27022:27017"